Document: xul-ext-xclear
Title: Debian xul-ext-xclear Manual
Author: <insert document author here>
Abstract: This manual describes what xul-ext-xclear is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xul-ext-xclear/xul-ext-xclear.sgml.gz

Format: postscript
Files: /usr/share/doc/xul-ext-xclear/xul-ext-xclear.ps.gz

Format: text
Files: /usr/share/doc/xul-ext-xclear/xul-ext-xclear.text.gz

Format: HTML
Index: /usr/share/doc/xul-ext-xclear/html/index.html
Files: /usr/share/doc/xul-ext-xclear/html/*.html
